### Get all
GET http://localhost:3000/coffees

### Create
POST http://localhost:3000/coffees 
Content-Type: application/json

{
	"name": "Douwe Egberts",
	"brand": "Douwe Egberts",
	"flavors": [
		"Dutch"
	]
}